name: nextmind_mobile
description: "Aplicativo Mobile do Projeto NextMind"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.8.0+1
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  flutter_command: ^7.2.2
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  http: ^1.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  logger: ^2.5.0
  lottie: ^3.3.1
  lucid_validation: ^1.2.4
  mask_text_input_formatter: ^2.9.0
  mockito: ^5.4.5
  result_command: ^1.3.0
  result_dart: ^2.0.0
  shared_preferences: ^2.5.1
  sqflite: ^2.4.1
  fade_shimmer: ^2.3.0
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_launcher_icons: "^0.14.3"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/nextmind/
    - assets/animations/
