// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByWYwl6jy9hyBffbi7Lcs6ASAW0_HwFbY',
    appId: '1:717856472169:web:d63a0b35878dfaadb0f6f8',
    messagingSenderId: '717856472169',
    projectId: 'nextmind-v2',
    authDomain: 'nextmind-v2.firebaseapp.com',
    storageBucket: 'nextmind-v2.firebasestorage.app',
    measurementId: 'G-GYP8GJV5Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0cfWek_7JlR27DkBxzhYT5OOsMoGoC1Y',
    appId: '1:717856472169:android:84e83d96e08bcd4cb0f6f8',
    messagingSenderId: '717856472169',
    projectId: 'nextmind-v2',
    storageBucket: 'nextmind-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmacwhZzcNiPOhZiqMmnf2nNppIsFPSB4',
    appId: '1:717856472169:ios:ff2355653a9ea007b0f6f8',
    messagingSenderId: '717856472169',
    projectId: 'nextmind-v2',
    storageBucket: 'nextmind-v2.firebasestorage.app',
    iosClientId: '717856472169-pgjl8j5ejlehgtphsvkp063s5564jnmk.apps.googleusercontent.com',
    iosBundleId: 'com.nextmind.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmacwhZzcNiPOhZiqMmnf2nNppIsFPSB4',
    appId: '1:717856472169:ios:77eb1b5d54c3ee3db0f6f8',
    messagingSenderId: '717856472169',
    projectId: 'nextmind-v2',
    storageBucket: 'nextmind-v2.firebasestorage.app',
    iosClientId: '717856472169-r7uloc378pb9704ob7rk59an92fjvl87.apps.googleusercontent.com',
    iosBundleId: 'com.example.nextmindMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByWYwl6jy9hyBffbi7Lcs6ASAW0_HwFbY',
    appId: '1:717856472169:web:d18ce1836fcdde85b0f6f8',
    messagingSenderId: '717856472169',
    projectId: 'nextmind-v2',
    authDomain: 'nextmind-v2.firebaseapp.com',
    storageBucket: 'nextmind-v2.firebasestorage.app',
    measurementId: 'G-HCQ4MKVH22',
  );

}